import Head from "next/head";
import { Inter } from "next/font/google";
import SearchBar from "@/components/SearchBar";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps(context: any) {
  const response = await fetch(`http://localhost:3000/api/hello`);
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Cool Recipe App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBar />
    </>
  );
}
